# TOÁN ỨNG DỤNG VÀ THỐNG KÊ
## Project 1: Gauss
### Họ và tên: Nguyễn Nam Khánh
### Lớp: 22_2
### MSSV: 22120157

### 1> Phép khử Gauss (Gauss Elimination)
<p>Viết hàm Gauss_elimination(A) trong đó</p>
<li>Input: A, là ma trận mở rộng của hệ phương trình Ax = b</li>
<li>Output: ma trận có dạng bậc thang có được từ ma trận A</li>
<p>Không được sử dụng các hàm có sẵn của thư viện để tìm ma trận bậc thang</p>

<strong>Giải thuật</strong>
<li>Bước 1: Duyệt lần lượt các cột, xác định cột có các phần tử không đồng thời bằng 0</li>
<li>Bước 2: Tìm phần tử khác 0 đầu tiên trong cột và hoán vị dòng đang xét với dòng chứa phần tử đó</li>
<li>Bước 3: Tìm các số k thích hợp sao cho k nhân với phần tử ở dòng đang xét cộng với các phần tử phía dưới bằng 0</li>
<li>Làm cho tới khi duyệt qua hết tất cả các cột, ta sẽ thu được ma trận bậc thang</li>

In [29]:
import numpy as np
np.set_printoptions(suppress=True)  # Không hiển thị số thực theo dạng số khoa học: 1e-xx

def Gauss_elimination(A):
    rows, cols = A.shape

    for c in range(cols):   # Duyệt qua từng cột
        if np.all(A[:, c] == 0):    # Nếu tất cả các phần tử trong cột c đều bằng 0 thì bỏ qua
            continue

        pivot = None
        for r in range(c, rows):    # Tìm phần tử pivot khác 0 đầu tiên trong cột c
            if A[r, c] != 0:
                pivot = r
                break

        if pivot is None:
            continue

        # Hoán vị dòng chứa pivot lên vị trí của dòng c
        A[[c, pivot]] = A[[pivot, c]]

        # Biến các phần tử dưới pivot về 0
        for r in range(c + 1, rows):   
            factor = A[r, c] / A[c, c]
            A[r] = A[r] -  factor * A[c]

    return A

In [30]:
# Các test case
# A = np.array(
#     [[1, 2, -1, -1], 
#     [2, 2, 1, 1],
#     [3, 5, -2, -1]], dtype=float)

# A = np.array(
#    [[1, -2, -1, 1], 
#    [2, -3, 1, 6],
#    [3, -5, 0, 7],
#    [1, 0, 5, 9]], dtype=float)
    
# A = np.array(
#     [[2, -4, -1, 1], 
#     [1, -3, 1, 1],
#     [3, -5, -3, 2]], dtype=float)

A = np.array(
     [[1, 2, 0, 2, 6],
     [3, 5, -1, 6, 17],
     [2, 4, 1, 2, 12],
     [2, 0, -7, 11, 7]], dtype=float)

# A = np.array(
#     [[2, -4, 6, 8],
#     [1, -1, 1, -1],
#     [1, -3, 4, 0]], dtype=float)
    

# A = np.array(
#     [[1, 2, -2, 3], 
#     [3, -1, 1, 1],
#     [-1, 5, -5, 5]], dtype=float)

print ('Ma tran ban dau: ')
print(A)
print ('\n')

print ('Ma tran bac thang:')
A = Gauss_elimination(A)
print(A)
print ('\n')

Ma tran ban dau: 
[[ 1.  2.  0.  2.  6.]
 [ 3.  5. -1.  6. 17.]
 [ 2.  4.  1.  2. 12.]
 [ 2.  0. -7. 11.  7.]]


Ma tran bac thang:
[[ 1.  2.  0.  2.  6.]
 [ 0. -1. -1.  0. -1.]
 [ 0.  0.  1. -2.  0.]
 [ 0.  0.  0.  1. -1.]]




### 2> Phép thế ngược (Back Substitution)
<p>Viết hàm back_substitution(A), trong đó</p>
<li>Input: A, là ma trận có dạng bậc thang thu được từ ma trận mở rộng của hệ phương trình Ax = b</li>
<li>Output: nghiệm của hệ phương trình (trường hợp nghiệm duy nhất/vô số nghiệm) hoặc thông báo hệ phương trình vô nghiệm</li>
<p>Không được sử dụng các hàm có sẵn của các thư viện để tìm nghiệm phương trình</p>

<strong>Giải thuật</strong>
<ul>
    <li>Bước 1: Tính hạng của ma trận Ab (ma trận mở rộng) và ma trận A</li>
    <li>
        <p>Bước 2: Biện luận nghiệm của hệ phương trình</p>
        <p>Nếu rank_A < rank_Ab thì hệ phương trình vô nghiệm</p>
        <p>
            Nếu rank_A = rank_Ab < n (số ẩn) thì hệ phương trình có vô số nghiệm. Để tìm nghiệm tổng quát, ta sẽ lưu các nghiệm dưới dạng vector và tìm
                                     số ẩn tự do của hệ.
            Ví dụ hệ có 1 ẩn tự do thì vector dạng [x, x] (x đầu lưu giá trị số, x thứ 2 lưu ẩn tự do. Ban đầu ta sẽ khởi tạo các vector bằng 0. Ví dụ hệ có 3 ẩn với x3 là ẩn tự do thì 
                                     x3 = [0, 1], số 4 lưu dạng vector là [4, 0], nên phương trình x2 + 3 * x3 = 4 với x3 là ẩn tự do thì 
            x2 = 4 - 3 * x3 = [4, 0] - 3 * [0, 1] = [4, -3]. Vector này chính là biểu diễn nghiệm của x2 = 4 - 3 * x3
            Giải lần lượt từ dưới lên giống phương pháp tìm nghiệm ở trường hợp thứ 3 rank_A = rank_Ab bên dưới để tìm các nghiệm còn lại
        </p>
        <p>
            Nếu rank_A = rank_Ab thì hệ phương trình có nghiệm duy nhất. Để tìm nghiệm ta duyệt từ dòng cuối lên đầu và giải phương trình
            A[i][i] * x[i] + s = A[i][n] với A[i][i] là phần tử trên đường chéo chính, s là tổng các phần tử trên đường chéo chính phía sau phần tử 
            A[i][i], rồi suy ra x[i] là nghiệm thứ i cần tìm
        </p>
    </li>
</ul>


In [31]:
def back_substitution(A):   # Giải hệ phương trình bằng phương pháp thế ngược
    rank_A = np.linalg.matrix_rank([row[:-1] for row in A]) # Hạng của ma trận không có cột cuối cùng
    rank_Ab = np.linalg.matrix_rank(A)  # Hạng của ma trận có cột cuối cùng

    n = A.shape[1] - 1  # Số biến/số ẩn

    if rank_A < rank_Ab:
        return "He phuong trinh vo nghiem"
    elif rank_A == rank_Ab < n:
        anTuDo = n - rank_A
        return f"He phuong trinh co vo so nghiem, voi {anTuDo} an tu do"
        #Phần hệ phương trình có vô số nghiệm này em chỉ có ý tưởng như giải thuật đã trình bày ở trên chứ code chưa được
    else:  
        print('He phuong trinh co nghiem duy nhat: ')
        x = [0] * n #Tao mang chua nghiem cua he phuong trinh
        for i in range(n-1, -1, -1): # Duyet tu dong cuoi cung den dong dau tien
            if A[i][i] != 0:    # Neu phan tu tren duong cheo chinh khac 0
                s = sum(A[i][j] * x[j] for j in range(i, n)) # Tinh tong cac phan tu tren duong cheo phia sau phan tu A[i][i]
                x[i] = (A[i][n] - s) / A[i][i]  # Tinh nghiem cua phuong trinh A[i][i] * x[i] + s =  A[i][n]
        return x

print(back_substitution(A))

He phuong trinh co nghiem duy nhat: 
[2.0, 3.0, -2.0, -1.0]
