# TOÁN ỨNG DỤNG THỐNG KÊ
### Lớp: 22_2
### MSSV: 22120157
### Họ tên: Nguyễn Nam Khánh
### Project 2: Gauss-Jordan

## 1. Viết hàm
<p>Viết hàm inverse(A), trong đó</p>
<li>Input: A là ma trận vuông.</li>
<li>
    Output: Ma trận nghịch đảo của ma trận A ban đầu (nếu có). Trường hợp không có ma trận nghịch đảo sẽ hiện thông báo 
    "Ma trận không khả nghịch"
</li>

### Yêu cầu:
<p>Phải sử dụng thuật toán Gauss-Jordan để tìm ma trận nghịch đảo. Không được sử dụng hàm có sẵn của thư viện để tìm ma trận nghịch đảo</p>

### Giải thuật
<li><strong>Bước 1: </strong>Tạo ma trận $(A|In)$ với n là hạng của ma trận A, $In$ là ma trận đơn vị </li>
<br>
<p>Thực hiện các bước sau cho cột thứ i, i=1,2,...n</p>
<li>
    <strong>Bước 2: </strong>Kiểm tra các số hạng từ dòng i đến dòng n của cột thứ i. Nếu chúng gồm toàn số 0, kết luận ma trận A không khả nghịch và giải thuật chấm dứt. Ngược lại, đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới dòng thứ j về dòng thứ i.
</li>
<br>
<li>
    <strong>Bước 3: </strong>Với số hạng ở dòng thứ i là a≠0, nhân dòng i với 1/a để nhận được số 1 (nằm trên đường chéo của A).
</li>
<br>
<li>
    <strong>Bước 4: </strong>Cộng một bội số thích hợp của dòng i với các dòng khác dòng i để biến các số hạng trên cột i về số 0 (trừ số hạng nằm ở dòng i). Trở lại bước 2 cho dòng kế, i = i + 1
Kết thúc giải thuật , ta nhận được ma trận $(In|A^{-1})$.
</li>

In [16]:
import numpy as np
np.set_printoptions(suppress=True)  # Không hiển thị số thực theo dạng 1e-xx

def inverse(A):
    #Tạo ma trận đơn vị kích thước bằng ma trận vuông A
    I = np.eye(A.shape[0])
    #Tạo ma trận bổ sung B = (A|I)
    B = np.hstack([A, I])
    rows, cols =  B.shape
    for c in range(cols):   # Duyệt qua từng cột
        if np.all(B[:, c] == 0):    # Nếu tất cả các phần tử trong cột c đều bằng 0 thì kết thúc
            return "Ma tran khong kha nghich"

        pivot = None
        for r in range(c, rows):    # Tìm phần tử pivot khác 0 đầu tiên trong cột c
            if B[r, c] != 0:
                pivot = r
                break

        if pivot is None:  
            continue

        # Hoán vị dòng chứa pivot lên vị trí của dòng c
        B[[c, pivot]] = B[[pivot, c]]
        
        # Nhân giá trị của dòng chứa pivot cho 1/pivot
        B[c] = B[c] / B[c, c]

        # Biến các phần tử trên dưới pivot về 0
        for r in range(rows):   
            if r == c:
                continue
            factor = B[r, c] / B[c, c]
            B[r] = B[r] -  factor * B[c]

    #Nếu ma trận B lúc này có dạng [I, A^-1] thì trả về ma trận nghịch đảo
    if np.all(B[:, :cols//2] == I):
        return B[:, cols//2:]
    else:
        return "Ma tran khong kha nghich"

            


### Ý tưởng thực hiện dựa trên giải thuật
<p>Ta sẽ viết hàm inverse(A) với A là ma trận vuông, trong hàm</p>
- Ta sẽ tạo ma trận mở rộng B = $(A|In)$
<p>Tiến hành duyệt qua các cột của ma trận B (các "-" dưới đây đều nằm trong vòng lặp)</p>
- Nếu cột đang xét có các phần tử đều bằng 0 thì trả về ma trận không khả nghịch. Nếu không thì đi tìm phần tử pivot khác 0 đầu
tiên và hoán vị dòng đang xét với dòng chứa phần tử pivot đó.
<br>
- Nhân pivot với 1/pivot để được phần tử 1 (là phần tử trên đường chéo chính của A)
<br>
- Duyệt qua từng hàng (trừ hàng chứa pivot) và cộng/trừ số k thích hợp để phần tử ở hàng đó bằng 0
<br>
<p>
    Ra khỏi vòng lặp, lúc này nếu ma trận B có nửa ma trận vuông đầu của B là ma trận đơn vị In thì nửa ma trận vuông sau là $A^-1$,
    nếu không thì ma trận không khả nghịch
</p>

## 2. In kết quả, đối chiếu với dùng thư viện

In [20]:
# A = np.array(
#     [[1, 1.5, -1.2],
#     [2, 3.7, 8],
#     [3.5, 2.5, 4]]
# )


A = np.array(
    [[1, -0.5, 2, -1.6],
     [5, -7, -3.2, -4.8],
     [6, 2, 8.9, 8.2],
     [5, 3.1, 4.2, 7.7]]
)

# A = np.array(
#     [[-1, 3, -4],
#      [2, 4, 1],
#      [-4, 2, -9]]
# )

# A = np.array(
#     [[1, 2, 3, 4],
#      [5, 6, 7, 8],
#      [9, 10, 11, 12],
#      [13, 14, 15, 16]]
# )


#Kiểm tra nếu A là ma trận vuông thì mới in
if A.shape[0] == A.shape[1]:
    print("Ma tran nghich dao khong dung thu vien numpy:")
    print(inverse(A))
    print("\n")

print("Ma tran nghich dao dung thu vien numpy:")
det = np.linalg.det(A)  # Tính định thức của ma trận A

if np.isclose(det, 0):  
    print("Ma tran khong kha nghich")
else:
    invA = np.linalg.inv(A)
    print(invA)

Ma tran nghich dao khong dung thu vien numpy: 

[[ 0.31754177  0.05992116 -0.19816888  0.31437315]
 [ 0.49739593 -0.09703248 -0.33549732  0.40015007]
 [ 0.09776151 -0.03766077  0.15748886 -0.17087816]
 [-0.45977073  0.02069742  0.17784843 -0.14216139]]


Ma tran nghich dao dung thu vien numpy: 
[[ 0.31754177  0.05992116 -0.19816888  0.31437315]
 [ 0.49739593 -0.09703248 -0.33549732  0.40015007]
 [ 0.09776151 -0.03766077  0.15748886 -0.17087816]
 [-0.45977073  0.02069742  0.17784843 -0.14216139]]
