# TOÁN ỨNG DỤNG THỐNG KÊ
## Lớp: 22_2
## MSSV: 22120157
## Họ tên: Nguyễn Nam Khánh
## Đồ án thực hành cuối kỳ HK2 2023-2024



### Câu 2: Markov Chain

#### Xử lý dữ liệu đề bài

![markov](https://i.imgur.com/CK4gM7o.png)

##### Dựa vào đề bài, do không thực hiện bất kỳ công tác bảo trì, sửa chữa nào trong 1 năm nên CSVC của các phòng học chỉ có thể xuống cấp thấp hơn (tối đa 1 cấp).  Số phòng ở trạng thái 4 sẽ không xuống cấp nữa vì đã ở tình trạng tệ nhất. Vì có 2 phòng trạng thái 4 nên suy ra có 2 – 1 = 1 phòng chuyển từ trạng thái 3 sang 4. Lúc này chỉ còn 3 – 1 = 2 phòng ở trạng thái 3, mà năm 2021 có 5 phòng trạng thái 3 suy ra có 5 – 2 = 3 phòng chuyển từ trạng thái 2 sang 3. Lúc này chỉ còn 12 – 3 = 9 phòng ở trạng thái 2, mà năm 2021 có 17 phòng trạng thái 2, suy ra có 17 – 9 = 8 phòng chuyển từ trạng thái 1 sang 2. Từ đó ta được bảng mô tả sự dịch chuyển trạng thái của phòng giữa năm 2020 và 2021 như trên

#### Câu a. Từ bảng trên, ta suy ra được ma trận chuyển trạng thái P của xích Markov

In [1]:
import numpy as np

P = np.array([
  [26/34, 0, 0, 0],
  [8/34, 9/12, 0, 0],
  [0, 3/12, 2/3, 0],
  [0, 0, 1/3, 1]
])
print(P)

[[0.76470588 0.         0.         0.        ]
 [0.23529412 0.75       0.         0.        ]
 [0.         0.25       0.66666667 0.        ]
 [0.         0.         0.33333333 1.        ]]


#### Câu b. Xác định vector phân phối xác suất ban đầu $\pi_0$

In [2]:
pi_0 = np.array([26/50, 17/50, 5/50, 2/50])
print(pi_0)

[0.52 0.34 0.1  0.04]


#### Câu c. Dự báo sự xuống cấp về CSVC của các phòng học tòa I trong vòng 15 năm tới, kể từ 2021

- Để tìm trạng thái của 50 phòng học trong 15 năm, ta sẽ đi tìm $\pi_{i}$ = $\pi_0$ * $P^{i}$ với i = 1, 2, ... 15

In [3]:
def round(x):
  return int(x + 0.5) if x > 0 else int(x - 0.5)

# Hàm nhân 2 ma trận
def matrix_multiply(A, B):
  rows_A, cols_A = A.shape
  rows_B, cols_B = B.shape
  result = np.zeros((rows_A, cols_B))
  for i in range(rows_A):
      for j in range(cols_B):
          for k in range(cols_A):
              result[i, j] += A[i, k] * B[k, j]
  return result

# Hàm nhân ma trận với vector
def matrix_multiply_vector(matrix, vector):
    result = np.zeros(matrix.shape[0])
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i] += matrix[i, j] * vector[j]
    return result

# Hàm tính lũy thừa ma trận
def matrix_power(matrix, power):
  result = matrix
  for _ in range(1, power):
      result = matrix_multiply(result, matrix)
  return result

# Hàm làm tròn mỗi phần tử của mảng sao cho tổng bằng target
# Ý tưởng của hàm này là ở mỗi bước, ta làm tròn 1 phần tử và lưu phần dư/thiếu (để đạt trạng thái số nguyên) vào biến temp
# Sau đó, ta cộng phần dư/thiếu này vào phần tử tiếp theo
# Khi đã làm tròn hết 4 phần tử, ta kiểm tra tổng của chúng có bằng target không, nếu có thì trả về mảng đã làm tròn
def round_to_target(array, target):
  temp = 0
  for i in range (0, 4):
    temp2 = array[i]
    array[i] = round(array[i] + temp)
    temp = temp + temp2 - array[i]

  sum = 0
  for i in range (0, 4):
    sum = sum + array[i]
  if sum == target:
    return array
       
# Hàm dự đoán phân phối của trạng thái sau 15 năm
# Ý tưởng của hàm này là nhân ma trận P mũ i với pi_0, i = 1, 2...15, sau đó làm tròn kết quả và in ra trạng thái dự đoán ở mỗi bước
def prediction():
  for i in range (1, 16):
    pi_i = 50 * matrix_multiply_vector(matrix_power(P, i), pi_0)
    pi_i_rounded = round_to_target(pi_i, 50)
    print(pi_i_rounded)

prediction()


[20. 19.  7.  4.]
[15. 19. 10.  6.]
[12. 17. 12.  9.]
[ 9. 16. 12. 13.]
[ 7. 14. 12. 17.]
[ 5. 12. 12. 21.]
[ 4. 10. 11. 25.]
[ 3.  9.  9. 29.]
[ 2.  8.  8. 32.]
[ 2.  6.  7. 35.]
[ 1.  5.  7. 37.]
[ 1.  4.  6. 39.]
[ 1.  3.  5. 41.]
[ 1.  2.  4. 43.]
[ 0.  3.  3. 44.]


![cau2](https://i.imgur.com/c6Mom5W.png)

#### Câu d. Xác định thời điểm phải phá hủy để xây lại/trùng tu tòa nhà (khi tất cả phòng học đều có CSVC xấu)

- Để tìm được thời điểm tất cả phòng học có CSVC xấu (trạng thái 4), tức là số phòng học ở 4 trạng thái phải lần lượt là: [0 0 0 50]. Ta
sẽ đi tìm cho tới khi đạt trạng thái đó và trả về i (là số năm kể từ năm 2021 để đạt được trạng thái [0 0 0 50]). Sau đó lấy năm bắt đầu là năm 2021 cộng với i sẽ thu được thời điểm để xây lại tòa nhà 

In [4]:
maxYearFrom2021 = 70

# Hàm tính khoảng thời gian cần để xây lại tòa nhà
def periodUntilRestore():
  for i in range (1, maxYearFrom2021):
    pi_i = 50 * matrix_multiply_vector(matrix_power(P, i), pi_0)
    pi_i_rounded = round_to_target(pi_i, 50)
    if(pi_i_rounded[3] == 50):
      return i
  return -1

period = periodUntilRestore()

yearStart = 2021
if period != -1:
    yearOfRestore = yearStart + period
    print("Thời điểm để xây lại tòa nhà là năm", yearOfRestore)
else:
    print("Lỗi")

Thời điểm để xây lại tòa nhà là năm 2048


#### Câu e. Xác định tuổi thọ của tòa nhà I

- Vì tòa nhà I được xây dựng và đưa vào sử dụng năm 2000 nên tuổi thọ của tòa nhà là thời điểm từ năm 2000 cho đến khi tất cả cơ sở vật chất của tòa nhà đều xuống cấp, tức là 50 phòng học đều ở trạng thái 4 (CSVC xấu). Ta đã tính được năm 2048 (yearOfStore) là năm cần xây lại tòa nhà. Vậy tuổi thọ của tòa nhà I sẽ là 2048 - 2000 = 48 (năm)

In [5]:
##Chạy câu d trước
yearOfConstruct = 2000
print("Tuổi thọ của tòa nhà I là: ", yearOfRestore - yearOfConstruct, "năm")

Tuổi thọ của tòa nhà I là:  48 năm


#### Mô tả các hàm
- Hàm round: dùng để làm tròn đến phần nguyên
- Hàm matrix_multiply(A, B): dùng để nhân 2 ma trận A, B
- Hàm matrix_power(P, i): dùng để tính ma trân $P^{i}$
- Hàm round_to_target(array, target): dùng để làm tròn các phần tử trong array đến phần nguyên sao cho tổng của chúng bằng target
- Hàm prediction(): dùng để in ra số lượng phòng học ở mỗi trạng thái trong 15 năm, từ năm 2021 đến 2035 
- Hàm periodUntilRestore(): dùng để tìm số năm kể từ năm 2021 để tòa nhà I được xây lại