# TOÁN ỨNG DỤNG THỐNG KÊ
### Lớp: 22_2
### MSSV: 22120157
### Họ tên: Nguyễn Nam Khánh
### Project 3: Gram-Schmidt

## 1. Viết chương trình in ra ma trận Q và R được phân rã từ ma trận A
<li>Input: A là ma trận có thể phân rã QR.</li>
<li>
    Output: Ma trận Q. Sau đó sử dụng đẳng thức A = QR để tìm ma trận R
</li>

### Yêu cầu:
<p>Phải sử dụng thuật toán Gram-Schmidt để phân rã ma trận. Không được sử dụng hàm có sẵn của thư viện để thực hiện phân rã QR</p>

### Giải thuật
<p><strong>Bước 1: </strong>Lấy kích thước m, n của ma trận A sau đó khởi tạo ma trận Q kích thước m x n để lưu các vector trực chuẩn hóa và ma trận R kích thước n x n để lưu hệ số các phép biến đổi</p>
<p>Thực hiện các bước 2- 6 sau cho các cột i = 1, 2...n</p>
<p><strong>Bước 2: </strong>Gán vector của cột thứ i của ma trận A cho vector v
</p>
<p><strong>Bước 3: </strong>Duyệt qua các cột từ j = 0 đến j = i - 1
    <li>Tính Rji bằng tích vô hướng của vector cột thứ j của Q và vector cột thứ i của A</li>
    <li>Cập nhật vector v = v - Rji * vector cột thứ j của Q</li>
</p>
<p><strong>Bước 5: </strong>Tính chuẩn vector cột thứ i của A và gán vào Rii của ma trận R</p>
<p><strong>Bước 6: </strong>Trực chuẩn hóa vector cột thứ i của A và gán vào vector cột thứ i của Q</p>
<p><strong>Bước 7: </strong>Trả về ma trận Q, R</p>


In [31]:
import numpy as np
np.set_printoptions(suppress=True)  # Không hiển thị số thực dạng scientific
def QR_decomposition(A):
    # Lấy số hàng và cột của ma trận A
    m, n = A.shape
    
    # Khởi tạo ma trận Q và R
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    # Lặp qua từng cột của ma trận A
    for i in range(n):
        # Lấy vector cột thứ j của A
        v = A[:, i]
        
        # Lặp qua các cột trước đó
        for j in range(i):
            R[j, i] = np.dot(Q[:, j], A[:, i])  # Tính R[j, i]
            v = v - R[j, i] * Q[:, j] # Cập nhật lại vector cột
        
        # Tính chuẩn của vector hiện tại
        R[i, i] = np.linalg.norm(v)
        
        # Trực chuẩn hóa vector và đưa vào ma trận Q
        Q[:, i] = v / R[i, i]
    
    return Q, R

# Test với ma trận A

# A = np.array(
#   [[1, 1, 1],
#     [2,-2, 2],
#     [1, 1, -1]]
# )

A = np.array(
  [[1, 1, 2],
    [2,-1, 1],
    [-2, 4, 1]]
)

# A = np.array(
#   [[1, 1, 1],
#     [2,2, 0],
#     [3, 0, 0],
#     [0 ,0 , 1]]
# )

Q, R = QR_decomposition(A)
print ("Ma trận A:")
print(A)
print("\nMa trận Q:")
print(Q)
print("\nMa trận R:")
print(R)


Ma trận A:
[[ 1  1  2]
 [ 2 -1  1]
 [-2  4  1]]

Ma trận Q:
[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]

Ma trận R:
[[ 3.         -3.          0.66666667]
 [ 0.          3.          2.33333333]
 [ 0.          0.          0.33333333]]


## 2. Mở rộng

### 2.1 Đối chiếu với dùng thư viện

In [32]:
Q, R = np.linalg.qr(A)

# In ma trận A, Q và R ( chạy code phần 1 trước)
print("Ma trận A:")
print(A)
print("\nMa trận Q:")
print(Q)
print("\nMa trận R:")
print(R)

Ma trận A:
[[ 1  1  2]
 [ 2 -1  1]
 [-2  4  1]]

Ma trận Q:
[[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]]

Ma trận R:
[[-3.          3.         -0.66666667]
 [ 0.         -3.         -2.33333333]
 [ 0.          0.          0.33333333]]


#### Từ việc thực hiện phân rã A = QR bằng thuật toán Gram-Schmidt không sử dụng thư viện và sử dụng thư viện numpy, ta thấy kết quả ma trận Q R ở 2 phần bị ngược dấu nhưng vẫn đúng với A = QR

### 2.2. Tìm hiểu và trình bày ứng dụng QR decomposition

- Hồi quy tuyến tính và các vấn đề bình phương tối thiểu: Phân rã QR thường được sử dụng trong các vấn đề hồi quy tuyến tính và xấp xỉ bình phương tối thiểu. Nó cho phép giải phương trình hệ tuyến tính một cách ổn định và hiệu quả, đặc biệt là khi xử lý các hệ quá xác định.
- Phân tích và xử lý dữ liệu: Phân rã QR có thể được sử dụng để phân tích và xử lý dữ liệu, bao gồm cả việc giảm chiều dữ liệu, xấp xỉ dữ liệu, và loại bỏ độ lệch (bias) từ các biến.
- Ứng dụng trong việc nén và xử lý hình ảnh: Phân rã QR có thể được sử dụng trong các thuật toán nén và xử lý hình ảnh, bao gồm việc giảm kích thước hình ảnh và loại bỏ nhiễu.
- Xử lý tín hiệu: Phân rã QR có thể được sử dụng cho các nhiệm vụ như lọc và làm sạch tín hiệu trong xử lý tín hiệu.
<p><strong>Kết luận: Theo những gì em tìm hiểu thì giảm chiều dữ liệu là ứng dụng quan trọng, phổ biến nhất của QR decomposition. 
    Việc giảm chiều dữ liệu này rất hữu ích trong nhiều ứng dụng như xử lý tín hiệu và hình ảnh, phân tích dữ liệu, nhận dạng mẫu, và máy học.
     Bằng cách loại bỏ hoặc giảm thiểu các thành phần không cần thiết, ta có thể giảm kích thước của dữ liệu mà vẫn giữ được những thông tin quan trọng, giúp cho việc tính toán và xử lý dữ liệu trở nên hiệu quả hơn.</strong></p>