# Đồ án 1
## Môn học: Toán ứng dụng & thống kê
### Lớp: CQ2022/2
### Họ tên: Phan Cao Nguyên
### MSSV: 21120299

---

## BÀI 1: PHÉP KHỬ GAUSS (GAUSSIAN ELIMINATION)

<strong> Với một hệ phương trình tuyến tính (*), thực hiện các yêu cầu sau </strong>
<li> Yêu cầu 1: Viết (*) dưới dạng phương trình ma trận A</li>
<li> Yêu cầu 2: Không dùng hàm có sẵn của thư viện</li>
<li> Yêu cầu 3: Viết hàm  Gauss_elimination(A), trong đó:  

- **Input:** Ma trận mở rộng A  
- **Output:** Ma trận có dạng bậc thang có được từ ma trận A
</li>

<strong> Giải thuật: </strong>
<li> Bước 1: Xác định cột đầu tiên không chứa toàn số 0. </li>
<li> Bước 2: Đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới về đầu cột nhận được ở bước 1. </li>
<li> Bước 3: Với số hạng đầu cột nhận được từ bước 2 là a khác 0, nhân dòng 1 với 1/a để nhận được một số dẫn đầu (leading 1). </li>
<li> Bước 4: Cộng một bội số thích hợp của dòng 1 với từng dòng dưới để biến các số hạng này về số 0. </li>
<li> Bước 5: Loại bỏ các dòng đã làm xong. Trở lại bước 1 cho ma trận con này. </li>

In [1]:
import numpy as np

def Gauss_elimination(A)->np.array:
    row = len(A) # Số dòng
    col = len(A[0]) # Số cột

    # Thực hiện phép khử Gauss
    column_now = 0;
    for i in range(row):
        # Tìm phần tử khác 0 tại cột i trong các hàng từ i đến n-1
        pivot_row = i # Hàng có phần tử khác 0
        
        while (column_now < col):
            while pivot_row < row and A[pivot_row][column_now] == 0:
                pivot_row += 1

            # Nếu không tìm thấy phần tử khác 0 bỏ qua cột column_now và tăng column_now lên 1
            if pivot_row == row:
                pivot_row = i
                column_now += 1
            else: break

        if (column_now == col): break 
        
        # Hoán đổi hàng có phần từ khác 0 và hàng i
        temp = np.array(A[pivot_row])
        A[pivot_row] = A[i]
        A[i] = temp
        
        # Biến đổi phần tử chéo A[i][i] thành 1
        pivot = A[i][column_now]
        
        for j in range(i, col):
            A[i][j] /= pivot

        # Loại bỏ phần tử A[l][i] trong các hàng từ i+1 đến n-1
        for l in range(i + 1, row):
            temp = A[l][column_now] # Cơ số để 2 hàng trừ nhau ra 0

            for j in range(i, col):
                A[l][j] -= temp * A[i][j]
                
        column_now += 1

    return A

In [2]:
A = np.array([[2.0, -2.0, -4.0, 2.0, 1.0], 
     [6.0, 3.0, -3.0, -3.0, 3.0], 
     [5.0, -4.0, 7.0, -12.0, 5.0],
     [-8.0, 4.0, -4.0, 9.0, -5.0]])

print(f"Ma trận mở rông đã nhâp: \n{A}")
matrix = Gauss_elimination(A)
print(f"Dạng ma trận bậc thang của ma trận mở rộng đã nhập: \n{matrix}") 

Ma trận mở rông đã nhâp: 
[[  2.  -2.  -4.   2.   1.]
 [  6.   3.  -3.  -3.   3.]
 [  5.  -4.   7. -12.   5.]
 [ -8.   4.  -4.   9.  -5.]]
Dạng ma trận bậc thang của ma trận mở rộng đã nhập: 
[[ 1.      -1.      -2.       1.       0.5    ]
 [ 0.       1.       1.      -1.       0.     ]
 [ 0.       0.       1.      -1.       0.15625]
 [ 0.       0.       0.       1.      -0.5    ]]


---

## BÀI 2: PHÉP THẾ NGƯỢC (BACK SUBSTITUTION)

<strong> Với một hệ phương trình tuyến tính (*), thực hiện các yêu cầu sau </strong>
<li> Yêu cầu 1: Viết (*) dưới dạng phương trình ma trận A được chuyển đổi về dưới dạng bậc thang</li>
<li> Yêu cầu 2: Không dùng hàm có sẵn của thư viện</li>
<li> Yêu cầu 3: Viết hàm back_substitution(A), trong đó:  

- **Input:** Ma trận mở rộng A|b với Ax=b
- **Output:** Nghiệm của hệ phương trình ( trường hợp nghiệm duy nhất/ vô số nghiệm ) hoặc thông báo hệ phương trình vô nghiệm.
</li>

<strong>Giải thuật:</strong>
<li> Bước 1. Biện luận trên các dòng gồm toàn số 0 của ma trận các hệ số. Nếu có một dòng gồm toàn số 0 của A mà hệ số vế phải (tự do) tương ứng là một số khác 0 thì kết luận hệ vô nghiệm và giải thuật chấm dứt. Ngược lại, bỏ tất cả các dòng gồm toàn số 0 (của ma trận các hệ số cũng như của vectơ các hệ số vế phải (tự do)) và chuyển qua bước 2.</li>
<li> Bước 2. Phép thế ngược (back substitution). Xác định các ẩn cơ sở là các ẩn tương ứng với các số dẫn đầu. Các ẩn còn lại được gọi là ẩn tự do (free variable). 

- Xét hai khả năng :
	- Không có ẩn tự do. Hệ có nghiệm duy nhất nhận được bằng cách giải từ dưới lên trên (backward).
	- Có ít nhất một ẩn tự do. Hệ có vô số nghiệm và nghiệm tổng quát nhận được bằng cách giải từ dưới lên tìm biểu thức của các ẩn dẫn đầu theo các tham số của ẩn tự do (tùy ý).
</li>

In [3]:
import string
from sympy import symbols

def isLeading(A: np.array, row: int, col: int) -> bool:
    result = bool
    check_sum = np.array(A[row][:col]).sum()

    if check_sum == 0:
        result = True
    else:
        result = False

    return result

def isZero(A: np.array) -> bool:
    row, col = A.shape
    result = True

    for i in range(row):
        for j in range(col):
            if A[i][i] != 0:
                result = False
                return result
            
    return result

def getMatrix(A: np.array) -> np.array:
    return (A.T)[0:-1].copy().T

def back_substitution(A) ->np.array:
    # Lấy số hàng và cột của ma trận
    row, col = A.shape
    col -= 1

    # Tạo một danh sách kết quả nghiệm
    x = np.zeros(col)

    # Xét từng hàng của ma trận bậc thang từ hàng cuối lên đầu
    for i in range(row - 1, -1, -1):
        colum = i

        while (A[i][colum] == 0 and colum < col):
            colum += 1

        if (colum == col):
            colum -= 1
        
        factor = A[i][colum] 
        const = A[i][col] # Giá trị hằng số
        
        # Nếu hệ số bằng 0 và hằng số khác 0 thì hệ phương trình vô nghiệm
        if factor == 0 and const != 0:
            print("Hệ phương trình vô nghiệm")
            return np.array(0)
        elif factor == 0 and const == 0:
            continue

        alphabet = symbols(list(string.ascii_lowercase))
        y = []
        index = 0

        # Duyệt trên đường bậc thang để đánh dấu nghiệm
        for i in range(col):
            i_rows = row - 1

            for _ in range(row):
                if A[i_rows][i] != 0:
                    if isLeading(A, i_rows, i):
                        y.append(0)
                    else:
                        y.append(alphabet[index])
                        index += 1
        
                    break
                else:
                    i_rows -= 1

        x = np.array(y)
        
        # Loại trừ trường hợp ma trận 0
        if isZero(A) == True:
            x = [alphabet[index] for index in range(col)]
            return x

    # back_substitution để tính nghiệm
    i = col - 1
    while i >= 0:
        i_rows = row - 1

        for _ in range(row):
            if A[i_rows][i] != 0:
                if isLeading(A, i_rows, i) == True:
                    s = x.dot(getMatrix(A)[i_rows])
                    x[i] = (A[i_rows][col] - s) / A[i_rows][i]

                break
            else:
                i_rows -= 1
        
        i -= 1

    return np.array(x).T

In [4]:
A = np.array([[1, 2, 4, 4],
    [0, 1, 2, 8],
    [0, 0, 0, 0]])


print(f"Ma trận mở rông (A|b) đã nhâp: \n{A}")

x = back_substitution(A)

if x.any():
        print("Nghiệm của hệ phương trình: ")
        for i in range(x.shape[0]):
            print(f"x{i+1} = {x[i]}")

Ma trận mở rông (A|b) đã nhâp: 
[[1 2 4 4]
 [0 1 2 8]
 [0 0 0 0]]
Nghiệm của hệ phương trình: 
x1 = -12
x2 = 8 - 2*a
x3 = a


## Dùng thư viện

In [5]:
from sympy import symbols, solve, Eq

# Khai báo biến
x1, x2, x3 = symbols('x1 x2 x3')

# Nhập hệ phương trình
eq1 = Eq(x1 + 2*x2 + 4*x3, 4)
eq2 = Eq(0*x1 + x2 + 2*x3, 8)
eq3 = Eq(0*x1 + 0*x2 + 0*x3, 0)

# Giải hệ phương trình
sol = solve((eq1, eq2, eq3), (x1, x2, x3))

# Hiển thị kết quả
print(sol)

{x1: -12, x2: 8 - 2*x3}
