# TOÁN ỨNG DỤNG VÀ THỐNG KÊ

## Bài tập 1: Giải hệ phương trình tuyến tính Ax=B bằng phép khử Gauss và phép thế ngược

|***Tên lớp: CQ2022/2***|
|---|
|***Họ và tên: Hoàng Hồ Nhật Minh***|
|***MSSV: 22120208***|

### Phần 1: Phép khử Gauss (Gauss Elimination)

**1. Yêu cầu:**


- **Input:** Nhập vào ma trận mở rộng A của hệ phương trình.
- **Output:** Ma trận có dạng bậc thang có được từ ma trận A.

**2. Giải thuật:**

- **Bước 1:** Xác định cột trái nhất chưa toàn số 0.
- **Bước 2:** Đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới về đầu cột nhận được ở **Bước 1**.
- **Bước 3:** Với số hạng đầu cột nhận được từ **Bước 2** là $a \neq 0$, nhân dòng chứa nó với $ \frac{1}{a} $ để có **số dẫn đầu 1**.
- **Bước 4:** Cộng một bội số thích hợp của dòng đầu cho từng dòng dưới để biến các số hạng bên dưới số dẫn đầu thành 0.
- **Bước 5:** Che dòng đầu đã làm xong. Lặp lại các bước cho đến khi được ma trận bậc thang.

#### Code:

In [1]:
import numpy as np

def Gauss_elimination(matrix):
    # Chuyển đổi ma trận sang kiểu float
    matrix = matrix.astype(float)
    m, n = matrix.shape

    for pivot in range(min(m, n)):
        # Tìm hàng đầu tiên có phần tử khác không ở cột hiện tại
        for swap in range(pivot, m):
            if matrix[swap, pivot] != 0:
                break
        else:
            continue

        # Đổi chỗ hai hàng nếu hàng đầu tiên có phần tử khác không không phải là hàng hiện tại
        if swap != pivot:
            matrix[[pivot, swap]] = matrix[[swap, pivot]]

        # Chia hàng hiện tại cho phần tử chính để biến nó thành 1
        matrix[pivot] /= matrix[pivot, pivot]

        # Trừ các hàng dưới đi một bội số của hàng hiện tại để biến các phần tử dưới phần tử chính thành 0
        for row in range(pivot + 1, m):
            matrix[row] -= matrix[pivot] * matrix[row, pivot] / matrix[pivot, pivot]

    return matrix


#A = np.array([[1,-1,1,-3,0],[2,-1,4,-2,0]])
A = np.array([[3,-3,3,-3],[-1,-5,2,4],[0,-4,2,2],[3,-1,2,-4]])
print (f"Ma trận mở rộng đã nhập: \n{A}")
print('Ma trận bậc thang của ma trận mở rộng đã nhập là:')
Matrix = Gauss_elimination(A)
print(Matrix)

Ma trận mở rộng đã nhập: 
[[ 3 -3  3 -3]
 [-1 -5  2  4]
 [ 0 -4  2  2]
 [ 3 -1  2 -4]]
Ma trận bậc thang của ma trận mở rộng đã nhập là:
[[ 1.  -1.   1.  -1. ]
 [-0.   1.  -0.5 -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


--------

### Phần 2: Phép thế ngược (Back substitution)


**1. Yêu cầu:**


- **Input:** Ma trận bậc thang có được từ mà trận mở rộng của hệ phương trình $Ax=b$.
- **Ouput:** Nghiệm của phương trình (trường hợp có duy nhất một hoặc vô số nghiệm), nếu vô nghiệm cần phải thông báo.

**2. Giải thuật:**

- **Bước 1:** Kiểm tra rank của ma trận A và ma trận mở rộng Aug.
- **Bước 2:** Xét 3 trường hợp:.
    - **TH1:** Rank(A) = Rank(Aug) = số ẩn. Kết luận hệ có nghiệm duy nhất và in ra nghiệm.
    - **TH2:** Rank(A) = Rank(Aug) < số ẩn. Kết luận hệ vô số nghiệm và in ra nghiệm tổng quát.
    - **TH3:** Rank(A) < Rank(Aug). Kết luận hệ vô nghiệm.

#### Code:

In [5]:

import sympy as sp

def to_rref(matrix):
    m, n = matrix.shape
    r = 0

    for c in range(n):
        if r == m:
            break
        pivot = np.argmax(np.abs(matrix[r:m, c])) + r
        if matrix[pivot, c] != 0:
            matrix[[r, pivot]] = matrix[[pivot, r]]
            matrix[r] = matrix[r] / matrix[r, c]
            for i in range(m):
                if i != r:
                    matrix[i] = matrix[i] - matrix[r] * matrix[i, c]
            r += 1
    return matrix

def Back_substitution(matrix):
    m, n = matrix.shape
    rref_matrix = to_rref(matrix.copy())
    
    # Kiểm tra xem hệ có nghiệm duy nhất hay vô số nghiệm
    rank_A = np.linalg.matrix_rank(matrix)
    rank_Aug = np.linalg.matrix_rank(rref_matrix)
    
    if rank_A == rank_Aug == n-1:
        # Hệ có một nghiệm duy nhất
        solution = [0 for _ in range(n-1)]
        for i in range(m-1, -1, -1):
            if rref_matrix[i, i] == 0:
                continue
            solution[i] = rref_matrix[i, -1] / rref_matrix[i, i]
            for k in range(i-1, -1, -1):
                rref_matrix[k, -1] -= rref_matrix[k, i] * solution[i]
        return "Hệ có một nghiệm duy nhất: " + str(solution)
    elif rank_A == rank_Aug < n-1:
        # Hệ có vô số nghiệm
        print_general_solution(matrix)
        return "Hệ có vô số nghiệm"
    else:
        # Hệ không có nghiệm
        return "Hệ không có nghiệm"

def print_general_solution(matrix):
    m, n = matrix.shape
    rref_matrix = to_rref(matrix.copy())
    
    free_variables = [sp.symbols(f'{chr(97 + i)}') for i in range(n-1)]
    general_solution = {var: 0 for var in free_variables}
    
    for i in range(m):
        for j in range(n):
            if rref_matrix[i, j] != 0:
                general_solution[free_variables[j]] = rref_matrix[i, -1]
                for k in range(j+1, n-1):
                    general_solution[free_variables[j]] -= rref_matrix[i, k]*free_variables[k]
                break
    
    for i in range(n-1):
        if general_solution[free_variables[i]] == 0:
            general_solution[free_variables[i]] = free_variables[i]
    
    print('Nghiệm tổng quát của hệ phương trình là:')
    for i in range(n-1):
        print(f'x{i+1} = {general_solution[free_variables[i]]}')
    
# Sử dụng hàm Back_substitution để kiểm tra và in ra nghiệm
print(Back_substitution(Matrix))



Nghiệm tổng quát của hệ phương trình là:
x1 = -0.5*c - 1.5
x2 = 0.5*c - 0.5
x3 = c
Hệ có vô số nghiệm
